baseURL = 'https://d4r18c3.github.io/blog/'
languageCode = 'en-us'
title = 'Blog'

theme = "m10c"

[params]
  author = "dc3"
  description = "A blog about all things technical."
  avatar = assets/avatar.png

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/d4r18c3"
