baseURL = 'https://d4r18c3.github.io/blog/'
languageCode = 'pt-br'
title = 'Blog1'

theme = 'anatole'

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
  author = 'Diego Crescêncio'
  description = 'Aprendendo em público. Uma jornada de aprendizado e recordações.'
  profilePicture = 'images/d.jpg'  
  contentratio = 0.7
  hidesidebar = false
  copyright = "Diego Crescêncio | 2020-{{ YEAR }}"
  customCss = ['css/custom.css']

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/diegocrescencio"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/d4r18c3"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:diego@crescencio.com.br"

[menu]

  [[menu.main]]
  name = "Início"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Artigos"
  weight = 200
  identifier = "posts"
  url = "/posts/"

 [[menu.main]]
  name = "Ordem cronológica"
  weight = 200
  identifier = "chronology"
  url = "/posts/"
  parent = "posts"

  [[menu.main]]
  name = "Categorias"
  weight = 220
  identifier = "categories"
  url = "/categories/"
  parent = "posts"

  [[menu.main]]
    identifier = "tags"
    weight = 290
    name = "Tags"
    url = "/tags/"
    parent = "posts"
    
  [[menu.main]]
  name = "Sobre"
  weight = 300
  identifier = "about"
  url = "/about/"



