baseURL = 'https://d4r18c3.github.io/blog/'
languageCode = 'pt-br'
title = 'Blog1'

theme = 'anatole'



[taxonomies]
  category = 'Epopéias'
  tag = 'teste'



[params]
  author = 'dc3'
  description = 'Aprendendo em público. Uma jornada de aprendizado e recordações.'
  profilePicture = 'images/d.jpg'

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/d4r18c3"
