baseURL = 'https://d4r18c3.github.io/blog/'
languageCode = 'en-us'
title = 'Blog1'

theme = 'anatole'



[params]
  author = 'dc3'
  description = 'A blog about all things technical.'
  profilePicture = 'images/avatar.png'

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/d4r18c3"
